### ISSUE TITLE
openrelik-server can't start

### ISSUE THREAD

**Issue by plonxyz** [openrelik/openrelik-server#34]
user@openrelik:~/openrelik$ docker compose up
[+] Running 9/0
 ✔ Container openrelik-worker-strings          Running                                                                               0.0s 
 ✔ Container openrelik-worker-extraction       Running                                                                               0.0s 
 ✔ Container openrelik-ui                      Running                                                                               0.0s 
 ✔ Container openrelik-mediator                Running                                                                               0.0s 
 ✔ Container openrelik-worker-plaso            Running                                                                               0.0s 
 ✔ Container openrelik-postgres                Running                                                                               0.0s 
 ✔ Container openrelik-worker-analyzer-config  Running                                                                               0.0s 
 ✔ Container openrelik-redis                   Running                                                                               0.0s 
 ✔ Container openrelik-worker-hayabusa         Running                                                                               0.0s 
Attaching to openrelik-mediator, openrelik-postgres, openrelik-redis, openrelik-server, openrelik-ui, openrelik-worker-analyzer-config, openrelik-worker-extraction, openrelik-worker-hayabusa, openrelik-worker-plaso, openrelik-worker-strings
openrelik-server    | INFO:     Started server process [1]
openrelik-server    | INFO:     Waiting for application startup.
openrelik-server    | ERROR:    Traceback (most recent call last):
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server    |     self.dialect.do_execute(
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server    |     cursor.execute(statement, parameters)
openrelik-server    | psycopg2.errors.UndefinedTable: relation "group" does not exist
openrelik-server    | LINE 2: FROM "group" 
openrelik-server    |              ^
openrelik-server    | 
openrelik-server    | 
openrelik-server    | The above exception was the direct cause of the following exception:
openrelik-server    | 
openrelik-server    | Traceback (most recent call last):
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 732, in lifespan
openrelik-server    |     async with self.lifespan_context(app) as maybe_state:
openrelik-server    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
openrelik-server    |     return await anext(self.gen)
openrelik-server    |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/openrelik/main.py", line 74, in lifespan
openrelik-server    |     await populate_everyone_group(db)
openrelik-server    |   File "/app/openrelik/main.py", line 48, in populate_everyone_group
openrelik-server    |     everyone_group = get_group_by_name_from_db(db, "Everyone")
openrelik-server    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/openrelik/datastores/sql/crud/group.py", line 59, in get_group_by_name_from_db
openrelik-server    |     return db.query(Group).filter(Group.name == name).first()
openrelik-server    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
openrelik-server    |     return self.limit(1)._iter().first()  # type: ignore
openrelik-server    |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
openrelik-server    |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
openrelik-server    |                                                   ^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
openrelik-server    |     return self._execute_internal(
openrelik-server    |            ^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
openrelik-server    |     result: Result[Any] = compile_state_cls.orm_execute_statement(
openrelik-server    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
openrelik-server    |     result = conn.execute(
openrelik-server    |              ^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
openrelik-server    |     return meth(
openrelik-server    |            ^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
openrelik-server    |     return connection._execute_clauseelement(
openrelik-server    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
openrelik-server    |     ret = self._execute_context(
openrelik-server    |           ^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
openrelik-server    |     return self._exec_single_context(
openrelik-server    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
openrelik-server    |     self._handle_dbapi_exception(
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
openrelik-server    |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server    |     self.dialect.do_execute(
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server    |     cursor.execute(statement, parameters)
openrelik-server    | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "group" does not exist
openrelik-server    | LINE 2: FROM "group" 
openrelik-server    |              ^
openrelik-server    | 
openrelik-server    | [SQL: SELECT "group".name AS group_name, "group".description AS group_description, "group".uuid AS group_uuid, "group".id AS group_id, "group".created_at AS group_created_at, "group".updated_at AS group_updated_at, "group".deleted_at AS group_deleted_at, "group".is_deleted AS group_is_deleted 
openrelik-server    | FROM "group" 
openrelik-server    | WHERE "group".name = %(name_1)s AND ("group".is_deleted = false OR "group".is_deleted IS NULL) 
openrelik-server    |  LIMIT %(param_1)s]
openrelik-server    | [parameters: {'name_1': 'Everyone', 'param_1': 1}]
openrelik-server    | (Background on this error at: https://sqlalche.me/e/20/f405)
openrelik-server    | 
openrelik-server    | ERROR:    Application startup failed. Exiting.
openrelik-server    | INFO:     Started server process [1]
openrelik-server    | INFO:     Waiting for application startup.
openrelik-server    | ERROR:    Traceback (most recent call last):
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server    |     self.dialect.do_execute(
openrelik-server    |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server    |     cursor.execute(statement, parameters)
openrelik-server    | psycopg2.errors.UndefinedTable: relation "group" does not exist
openrelik-server                  | LINE 2: FROM "group" 
openrelik-server                  |              ^
openrelik-server                  | 
openrelik-server                  | 
openrelik-server                  | The above exception was the direct cause of the following exception:
openrelik-server                  | 
openrelik-server                  | Traceback (most recent call last):
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 732, in lifespan
openrelik-server                  |     async with self.lifespan_context(app) as maybe_state:
openrelik-server                  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
openrelik-server                  |     return await anext(self.gen)
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/openrelik/main.py", line 74, in lifespan
openrelik-server                  |     await populate_everyone_group(db)
openrelik-server                  |   File "/app/openrelik/main.py", line 48, in populate_everyone_group
openrelik-server                  |     everyone_group = get_group_by_name_from_db(db, "Everyone")
openrelik-server                  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/openrelik/datastores/sql/crud/group.py", line 59, in get_group_by_name_from_db
openrelik-server                  |     return db.query(Group).filter(Group.name == name).first()
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
openrelik-server                  |     return self.limit(1)._iter().first()  # type: ignore
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
openrelik-server                  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
openrelik-server                  |                                                   ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
openrelik-server                  |     return self._execute_internal(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
openrelik-server                  |     result: Result[Any] = compile_state_cls.orm_execute_statement(
openrelik-server                  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
openrelik-server                  |     result = conn.execute(
openrelik-server                  |              ^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
openrelik-server                  |     return meth(
openrelik-server                  |            ^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
openrelik-server                  |     return connection._execute_clauseelement(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
openrelik-server                  |     ret = self._execute_context(
openrelik-server                  |           ^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
openrelik-server                  |     return self._exec_single_context(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
openrelik-server                  |     self._handle_dbapi_exception(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
openrelik-server                  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server                  |     self.dialect.do_execute(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server                  |     cursor.execute(statement, parameters)
openrelik-server                  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "group" does not exist
openrelik-server                  | LINE 2: FROM "group" 
openrelik-server                  |              ^
openrelik-server                  | 
openrelik-server                  | [SQL: SELECT "group".name AS group_name, "group".description AS group_description, "group".uuid AS group_uuid, "group".id AS group_id, "group".created_at AS group_created_at, "group".updated_at AS group_updated_at, "group".deleted_at AS group_deleted_at, "group".is_deleted AS group_is_deleted 
openrelik-server                  | FROM "group" 
openrelik-server                  | WHERE "group".name = %(name_1)s AND ("group".is_deleted = false OR "group".is_deleted IS NULL) 
openrelik-server                  |  LIMIT %(param_1)s]
openrelik-server                  | [parameters: {'name_1': 'Everyone', 'param_1': 1}]
openrelik-server                  | (Background on this error at: https://sqlalche.me/e/20/f405)
openrelik-server                  | 
openrelik-server                  | ERROR:    Application startup failed. Exiting.
openrelik-server                  | INFO:     Started server process [1]
openrelik-server                  | INFO:     Waiting for application startup.
openrelik-server                  | ERROR:    Traceback (most recent call last):
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server                  |     self.dialect.do_execute(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server                  |     cursor.execute(statement, parameters)
openrelik-server                  | psycopg2.errors.UndefinedTable: relation "group" does not exist
openrelik-server                  | LINE 2: FROM "group" 
openrelik-server                  |              ^
openrelik-server                  | 
openrelik-server                  | 
openrelik-server                  | The above exception was the direct cause of the following exception:
openrelik-server                  | 
openrelik-server                  | Traceback (most recent call last):
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 732, in lifespan
openrelik-server                  |     async with self.lifespan_context(app) as maybe_state:
openrelik-server                  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
openrelik-server                  |     return await anext(self.gen)
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/openrelik/main.py", line 74, in lifespan
openrelik-server                  |     await populate_everyone_group(db)
openrelik-server                  |   File "/app/openrelik/main.py", line 48, in populate_everyone_group
openrelik-server                  |     everyone_group = get_group_by_name_from_db(db, "Everyone")
openrelik-server                  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/openrelik/datastores/sql/crud/group.py", line 59, in get_group_by_name_from_db
openrelik-server                  |     return db.query(Group).filter(Group.name == name).first()
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
openrelik-server                  |     return self.limit(1)._iter().first()  # type: ignore
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
openrelik-server                  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
openrelik-server                  |                                                   ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
openrelik-server                  |     return self._execute_internal(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
openrelik-server                  |     result: Result[Any] = compile_state_cls.orm_execute_statement(
openrelik-server                  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
openrelik-server                  |     result = conn.execute(
openrelik-server                  |              ^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
openrelik-server                  |     return meth(
openrelik-server                  |            ^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
openrelik-server                  |     return connection._execute_clauseelement(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
openrelik-server                  |     ret = self._execute_context(
openrelik-server                  |           ^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
openrelik-server                  |     return self._exec_single_context(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
openrelik-server                  |     self._handle_dbapi_exception(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
openrelik-server                  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server                  |     self.dialect.do_execute(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server                  |     cursor.execute(statement, parameters)
openrelik-server                  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "group" does not exist
openrelik-server                  | LINE 2: FROM "group" 
openrelik-server                  |              ^
openrelik-server                  | 
openrelik-server                  | [SQL: SELECT "group".name AS group_name, "group".description AS group_description, "group".uuid AS group_uuid, "group".id AS group_id, "group".created_at AS group_created_at, "group".updated_at AS group_updated_at, "group".deleted_at AS group_deleted_at, "group".is_deleted AS group_is_deleted 
openrelik-server                  | FROM "group" 
openrelik-server                  | WHERE "group".name = %(name_1)s AND ("group".is_deleted = false OR "group".is_deleted IS NULL) 
openrelik-server                  |  LIMIT %(param_1)s]
openrelik-server                  | [parameters: {'name_1': 'Everyone', 'param_1': 1}]
openrelik-server                  | (Background on this error at: https://sqlalche.me/e/20/f405)
openrelik-server                  | 
openrelik-server                  | ERROR:    Application startup failed. Exiting.
openrelik-server                  | INFO:     Started server process [1]
openrelik-server                  | INFO:     Waiting for application startup.
openrelik-server                  | ERROR:    Traceback (most recent call last):
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server                  |     self.dialect.do_execute(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server                  |     cursor.execute(statement, parameters)
openrelik-server                  | psycopg2.errors.UndefinedTable: relation "group" does not exist
openrelik-server                  | LINE 2: FROM "group" 
openrelik-server                  |              ^
openrelik-server                  | 
openrelik-server                  | 
openrelik-server                  | The above exception was the direct cause of the following exception:
openrelik-server                  | 
openrelik-server                  | Traceback (most recent call last):
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 732, in lifespan
openrelik-server                  |     async with self.lifespan_context(app) as maybe_state:
openrelik-server                  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
openrelik-server                  |     return await anext(self.gen)
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/openrelik/main.py", line 74, in lifespan
openrelik-server                  |     await populate_everyone_group(db)
openrelik-server                  |   File "/app/openrelik/main.py", line 48, in populate_everyone_group
openrelik-server                  |     everyone_group = get_group_by_name_from_db(db, "Everyone")
openrelik-server                  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/openrelik/datastores/sql/crud/group.py", line 59, in get_group_by_name_from_db
openrelik-server                  |     return db.query(Group).filter(Group.name == name).first()
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
openrelik-server                  |     return self.limit(1)._iter().first()  # type: ignore
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
openrelik-server                  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
openrelik-server                  |                                                   ^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
openrelik-server                  |     return self._execute_internal(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
openrelik-server                  |     result: Result[Any] = compile_state_cls.orm_execute_statement(
openrelik-server                  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
openrelik-server                  |     result = conn.execute(
openrelik-server                  |              ^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
openrelik-server                  |     return meth(
openrelik-server                  |            ^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
openrelik-server                  |     return connection._execute_clauseelement(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
openrelik-server                  |     ret = self._execute_context(
openrelik-server                  |           ^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
openrelik-server                  |     return self._exec_single_context(
openrelik-server                  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
openrelik-server                  |     self._handle_dbapi_exception(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
openrelik-server                  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
openrelik-server                  |     self.dialect.do_execute(
openrelik-server                  |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
openrelik-server                  |     cursor.execute(statement, parameters)
openrelik-server                  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "group" does not exist
openrelik-server                  | LINE 2: FROM "group" 
openrelik-server                  |              ^
openrelik-server                  | 
openrelik-server                  | [SQL: SELECT "group".name AS group_name, "group".description AS group_description, "group".uuid AS group_uuid, "group".id AS group_id, "group".created_at AS group_created_at, "group".updated_at AS group_updated_at, "group".deleted_at AS group_deleted_at, "group".is_deleted AS group_is_deleted

**Comment by drewhjelm** [comment]
I resolved this by killing the openrelik-server docker container and running the SQL bootstrap scripts

`docker exec openrelik-server bash -c "(cd /app/openrelik/datastores/sql && alembic upgrade head)"`
